// <auto-generated />
using CloudCity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudCity.Migrations
{
    [DbContext(typeof(CloudCityContext))]
    [Migration("20220121181324_RecreateMigrations")]
    partial class RecreateMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CloudCity.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            Description = "The upper levels of Cloud City are given over primarily to resorts, hotels, casinos, museums, theaters, boutiques, restaurants, and other attractions for the sector's well-to-do.",
                            Name = "Tourist District"
                        },
                        new
                        {
                            DistrictId = 2,
                            Description = "Immediately accessible from the majority of Cloud City's landing bays and platforms, Port Town occupies levels 121 through 160 of the facility.",
                            Name = "Port Town"
                        },
                        new
                        {
                            DistrictId = 3,
                            Description = "These regions consist of tibanna gas mining and processing equipment, including carbonite freezing facilities. The industrial levels also include the necessities for maintaining Cloud City's operations.",
                            Name = "Industrial District"
                        });
                });

            modelBuilder.Entity("CloudCity.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LocationId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Description = "In a city well known for its elegant, high-class hotels, the Yarith Bespin stands out as the most elegant and highest class of them all.",
                            DistrictId = 1,
                            Level = 1,
                            Name = "The Yarith Bespin"
                        },
                        new
                        {
                            LocationId = 2,
                            Description = "Figg Hall is a public space for visitors and residents to speak with representatives of Cloud City's government.",
                            DistrictId = 1,
                            Level = 1,
                            Name = "Figg Hall"
                        },
                        new
                        {
                            LocationId = 3,
                            Description = "Located on level 121, almost exactly in the center of Port Town, is a long, wide corridor that runs from the outermost edges of the Floating Home platform to the central shaft used as an semi-open marketplace.",
                            DistrictId = 2,
                            Level = 121,
                            Name = "Market Row"
                        },
                        new
                        {
                            LocationId = 4,
                            Description = "Located on level 124, Landing Bay 124A is in all respects a perfectly normal and average Port Town landing bay for Cloud City.",
                            DistrictId = 2,
                            Level = 124,
                            Name = "Landing Bay 124A"
                        },
                        new
                        {
                            LocationId = 5,
                            Description = "\"Finest speeders on Bespin! You can trust me, I'm Honest Grek!\"",
                            DistrictId = 3,
                            Level = 128,
                            Name = "Honest Grek's Speeders"
                        },
                        new
                        {
                            LocationId = 6,
                            Description = "Negri is an Ugnaught male who oversees the operations of Process Vane 5. Negri's vane is the least efficient vane in the entire complex, with the most unscheduled downtime for \"maintenance.\" In reality, Negri is perfectly willing to take a little money under the table to freeze anything a client might want in one of his carbonite sledges.",
                            DistrictId = 3,
                            Level = 1,
                            Name = "Negri's Processing Vane"
                        });
                });

            modelBuilder.Entity("CloudCity.Models.Location", b =>
                {
                    b.HasOne("CloudCity.Models.District", "District")
                        .WithMany("Locations")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("CloudCity.Models.District", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
